#!/usr/bin/env python3
"""Render the two Credentials lists from hugo/data/credentials.yaml.

Two lists, Education and Certifications: each entry as its issuer or university
names it, and the date it was earned. No status, no notes -- the dates are the story.

    build_credentials.py           write the list into index.html
    build_credentials.py --check   fail if index.html says anything else

The source of truth is hugo/data/credentials.yaml, which is stated the way
content/docs/Curriculum Vitae/Credentials.md states it.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]          # tools/ -> typographic-index/ -> specs/ -> repo
INDEX = HERE.parent / "index.html"
DATA = REPO / "hugo" / "data" / "credentials.yaml"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

START = re.compile(r"[ \t]*<!-- creds:start.*?-->", re.DOTALL)
END = re.compile(r"[ \t]*<!-- creds:end -->")
TITLE = re.compile(r'<h2 class="ptitle" id="title-credentials"[^>]*>([^<]*)</h2>')


def esc(text: str) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;"))


def date_label(value: str) -> str:
    """'2026-06-05' -> 'Jun 5, 2026';  '2024-01' -> 'Jan 2024'."""
    parts = [int(p) for p in str(value).split("-")]
    month = MONTHS[parts[1] - 1]
    return f"{month} {parts[2]}, {parts[0]}" if len(parts) > 2 else f"{month} {parts[0]}"


def load() -> dict:
    return yaml.safe_load(DATA.read_text(encoding="utf-8"))


def render() -> str:
    creds = load()["credentials"]
    # Two lists. The degree is not a certification and sorts to the bottom of a date
    # order, so it is separated rather than ranked: Education first, then the
    # certifications newest first. A heading is only emitted for a group that has rows,
    # so removing every certification leaves a page with one list and no empty heading.
    groups = [
        ("Education", [c for c in creds if c.get("kind") == "education"]),
        ("Certifications", sorted((c for c in creds if c.get("kind") != "education"),
                                  key=lambda c: str(c["earned"]), reverse=True)),
    ]
    out: list[str] = []
    for heading, rows in groups:
        if not rows:
            continue
        out.append(f'      <p class="subhead" data-inview>{esc(heading)}</p>')
        out.append('      <ul class="creds">')
        for c in rows:
            out.append('        <li class="cred">')
            out.append(f'          <span class="cred__name">{esc(c["name"])}</span>')
            out.append(f'          <span class="cred__meta">{date_label(c["earned"])}</span>')
            out.append("        </li>")
        out.append("      </ul>")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def block(body: str) -> str:
    return ('      <!-- creds:start \u2014 from hugo/data/credentials.yaml; '
            'generated by tools/build_credentials.py, not hand-written -->\n'
            + body + "      <!-- creds:end -->")


def splice(text: str) -> str:
    start, end = START.search(text), END.search(text)
    if not start or not end:
        raise SystemExit("index.html has no creds:start / creds:end markers")
    return text[:start.start()] + block(render()) + text[end.end():]


def check() -> list[str]:
    text = INDEX.read_text(encoding="utf-8")
    problems = []
    if splice(text) != text:
        listed = len(re.findall(r'<li class="cred">', text))
        want = len(load()["credentials"])
        # Say what actually differs. A count mismatch is the common case, but a name or
        # a date can drift with the counts identical -- which is how a literal "\u2014"
        # once reached the page while both sides still said seven.
        detail = (f"{listed} rows on the page, {want} in the data" if listed != want
                  else f"{listed} rows either way, but the text differs")
        problems.append(f"the page does not match hugo/data/credentials.yaml ({detail})")
    m = TITLE.search(text)
    want = load()["title"]
    if not m:
        problems.append("the panel has no title to check")
    elif m.group(1).strip() != want:
        problems.append(f"the panel is titled '{m.group(1).strip()}', the data says '{want}'")
    return problems


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    if args.check:
        problems = check()
        for p in problems:
            print(f"  FAIL  {p}")
        return 1 if problems else 0

    text = INDEX.read_text(encoding="utf-8")
    new = splice(text)
    if new != text:
        INDEX.write_text(new, encoding="utf-8")
    data = load()
    kinds = [c.get("kind") for c in data["credentials"]]
    print(f"wrote {len(kinds)} credentials into index.html "
          f"({kinds.count('education')} education, {kinds.count('certification')} certifications), "
          f"titled \"{data['title']}\"")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
