#!/usr/bin/env python3
"""Render the Credentials panel from hugo/data/credentials.yaml.

The lists on the Credentials page are the one place in this design where the
order matters and a mistake is a false claim about Graham's own record, so they
are not hand-written. This reads the data, writes the block between the
`creds:start` and `creds:end` markers in index.html, and -- with --check --
fails if index.html says anything else.

    build_credentials.py           write the block
    build_credentials.py --check   fail if the block is stale

The source of truth is hugo/data/credentials.yaml. The dates in it come from
content/docs/Curriculum Vitae/Credentials.md; the status does not, because that
file does not record expiry. See the header of the YAML.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]          # tools/ -> typographic-index/ -> specs/ -> repo
INDEX = HERE.parent / "index.html"
DATA = REPO / "hugo" / "data" / "credentials.yaml"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

START = re.compile(r"[ \t]*<!-- creds:start.*?-->", re.DOTALL)
END = re.compile(r"[ \t]*<!-- creds:end -->")


def month(value: str) -> str:
    """'2026-06' -> 'Jun 2026'."""
    year, mon = str(value).split("-")[:2]
    return f"{MONTHS[int(mon) - 1]} {year}"


def esc(text: str) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;"))


def load() -> dict:
    return yaml.safe_load(DATA.read_text(encoding="utf-8"))


def render() -> str:
    data = load()
    creds = data["credentials"]
    blurbs = {g["group"]: g.get("blurb", "") for g in data["groups"]}
    order = [g["group"] for g in data["groups"]]

    out: list[str] = []
    first = True
    for group in order:
        rows = sorted((c for c in creds if c["status"] == group),
                      key=lambda c: str(c["earned"]), reverse=True)
        if not rows:
            continue
        if not first:
            out.append('      <div class="rule" data-inview></div>')
            out.append("")
        first = False
        blurb = blurbs.get(group, "")
        out.append(f'      <p class="subhead" data-inview>{esc(group)}'
                   + (f'<span class="subhead__note">&middot;&nbsp;{esc(blurb)}</span>' if blurb else "")
                   + "</p>")
        out.append('      <ul class="creds">')
        for c in rows:
            mod = " cred--lapsed" if group == "Past" else ""
            out.append(f'      <li class="cred{mod}">'.replace("      <li", "        <li"))
            out.append(f'          <span class="cred__name">{esc(c["name"])}</span>')
            if c.get("short"):
                out.append(f'          <span class="cred__short">{esc(c["short"])}</span>')
            out.append(f'          <span class="cred__meta">{esc(c["issuer"])} '
                       f'&middot; {month(c["earned"])}</span>')
            if c.get("note"):
                out.append(f'          <span class="cred__note">{esc(c["note"])}</span>')
            out.append("        </li>")
        out.append("      </ul>")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def block(body: str) -> str:
    return ('      <!-- creds:start \u2014 from hugo/data/credentials.yaml; '
            'generated by tools/build_credentials.py, not hand-written -->\n'
            + body + "\n      <!-- creds:end -->")


def splice(text: str) -> str:
    start = START.search(text)
    end = END.search(text)
    if not start or not end:
        raise SystemExit("index.html has no creds:start / creds:end markers")
    return text[:start.start()] + block(render()) + text[end.end():]


def check() -> list[str]:
    text = INDEX.read_text(encoding="utf-8")
    want = splice(text)
    if want == text:
        return []
    data = load()
    got = len(re.findall(r'class="cred[ "]', text))
    return [f"the Credentials panel is stale: index.html lists {got} credentials, "
            f"hugo/data/credentials.yaml defines {len(data['credentials'])}"]


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    if args.check:
        problems = check()
        for p in problems:
            print(f"  FAIL  {p}")
        return 1 if problems else 0

    text = INDEX.read_text(encoding="utf-8")
    new = splice(text)
    if new != text:
        INDEX.write_text(new, encoding="utf-8")
    data = load()
    per: dict[str, int] = {}
    for c in data["credentials"]:
        per[c["status"]] = per.get(c["status"], 0) + 1
    print(f"wrote {len(data['credentials'])} credentials into index.html "
          + " ".join(f"({k} {v})" for k, v in per.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
